# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "email": "dede@dede.com" ,
   "password": "111111"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "dede@dede.com" ,
   "password": "111111"
}

###

# @name profile

GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1MjVkZGJmLThjNWItNDdhZS04YTkxLWQyNjEzNGYyZWRjZCIsImlhdCI6MTY1NjQ1NDQ2MywiZXhwIjoxNjU2NDU0NzYzfQ.uL9gRxaBH2cCuAQ3zNydIYJpQHRbb3hAiB7O4d8fTns
###

