# @name CriandoUsuário

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "email": "Alessandra@hotmail.com",
    "name": "Alessandra",
    "password": "123456",
    "role": "ADMIN"
}

###
